   name: main
   on:
      push
   jobs:
     build:
       runs-on: ubuntu-latest
       steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-node@v1
          - run: npm install
          - run: make lint
          - name: run tests
            run: make test
     coverage:
        runs-on: ubuntu-latest
        steps:
          - name: Test & publish code coverage
            uses: paambaati/codeclimate-action@v3.1.0
            env:
              CC_TEST_REPORTER_ID: ${{ secrets.TEST_ID }}
            with:
             coverageCommand: make test
             debug: false

      
